apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secure-operator-sa
  namespace: default
